# Generated by Django 3.0.1 on 2020-01-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('age', models.SmallIntegerField()),
                ('breed', models.CharField(default='беспородный', max_length=50)),
                ('description', models.TextField()),
                ('receipted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.ImageField(blank=True, upload_to='book_avatars/%Y/%m/%d')),
                ('kindofanimal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='shelter.KindOfAnimal')),
            ],
        ),
    ]
