# Generated by Django 3.0.1 on 2020-01-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.SmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='беспородный', max_length=50, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kindofanimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='shelter.KindOfAnimal', verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='Пол'),
        ),
    ]
